### ISSUE TITLE
Downloads page not updating

### ISSUE THREAD

**Issue by scottcain** [cancogen-virus-seq/portal#195]
The last update on the downloads page is from Feb 10 with 184232 sample.  The current number of samples reported on the main page is 188201. Please find the errant process and give it a kick!

**Comment by jaserud** [comment]
The service was stuck with an error (logs pasted below). The error indicates that for some reason service ran out of connections to make to our object storage. Most likely problem, the services isn't releasing old connections so the connection pool is exhausted. It has been running for 16 days with no restarts.
```
2022-02-18 18:03:53.005  INFO 1 --- [or-http-epoll-1] Contributors::getContributors            : | onComplete()
2022-02-18 19:06:56.186  INFO 1 --- [     parallel-1] KafkaEventEmitter::emit                  : | onNext(2022-02-18T19:06:26.142412Z)
2022-02-18 19:06:56.194  INFO 1 --- [     parallel-1] InstantToArchiveBuildRequest             : | onSubscribe([Fuseable] FluxContextWrite.ContextWriteSubscriber)
2022-02-18 19:06:56.194  INFO 1 --- [     parallel-1] InstantToArchiveBuildRequest             : | request(unbounded)
2022-02-18 19:06:56.200  INFO 1 --- [     parallel-1] Files::createAllArchiveDisposable        : | onNext(2022-02-18T19:06:26.142412Z)
2022-02-18 19:06:56.803  INFO 1 --- [tor-tcp-epoll-1] InstantToArchiveBuildRequest             : | onNext(org.cancogenvirusseq.singularity.components.model.ArchiveBuildRequest@2136fcd6)
2022-02-18 19:06:56.810  INFO 1 --- [tor-tcp-epoll-1] d::downloadAndArchiveFunctionWithInstant : | onSubscribe([Fuseable] FluxMapFuseable.MapFuseableSubscriber)
2022-02-18 19:06:56.810  INFO 1 --- [tor-tcp-epoll-1] ArchiveBuildRequestToArchive             : | onSubscribe([Fuseable] FluxContextWrite.ContextWriteSubscriber)
2022-02-18 19:06:56.810  INFO 1 --- [tor-tcp-epoll-1] ArchiveBuildRequestToArchive             : | request(unbounded)
2022-02-18 19:06:56.810  INFO 1 --- [tor-tcp-epoll-1] d::downloadAndArchiveFunctionWithInstant : | request(256)
2022-02-18 19:06:56.813  INFO 1 --- [tor-tcp-epoll-1] InstantToArchiveBuildRequest             : | onComplete()
2022-02-18 19:10:46.600 ERROR 1 --- [tyEventLoop-0-0] d::downloadAndArchiveFunctionWithInstant : | onError(software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: Acquire operation took longer than the configured maximum time. This indicates that a request cannot get a connection from the pool within the specified maximum time. This can be due to high request rate.
Consider taking any of the following actions to mitigate the issue: increase max connections, increase acquire timeout, or slowing the request rate.
Increasing the max connections can increase client throughput (unless the network interface is already fully utilized), but can eventually start to hit operation system limitations on the number of file descriptors used by the process. If you already are fully utilizing your network interface or cannot further increase your connection count, increasing the acquire timeout gives extra time for requests to acquire a connection before timing out. If the connections doesn't free up, the subsequent requests will still timeout.
If the above mechanisms are not able to fix the issue, try smoothing out your requests so that large traffic bursts cannot overload the client, being more efficient with the number of times you need to call AWS, or by increasing the number of hosts sending requests.)
2022-02-18 19:10:46.605 ERROR 1 --- [tyEventLoop-0-0] d::downloadAndArchiveFunctionWithInstant : 

software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: Acquire operation took longer than the configured maximum time. This indicates that a request cannot get a connection from the pool within the specified maximum time. This can be due to high request rate.
Consider taking any of the following actions to mitigate the issue: increase max connections, increase acquire timeout, or slowing the request rate.
Increasing the max connections can increase client throughput (unless the network interface is already fully utilized), but can eventually start to hit operation system limitations on the number of file descriptors used by the process. If you already are fully utilizing your network interface or cannot further increase your connection count, increasing the acquire timeout gives extra time for requests to acquire a connection before timing out. If the connections doesn't free up, the subsequent requests will still timeout.
If the above mechanisms are not able to fix the issue, try smoothing out your requests so that large traffic bursts cannot overload the client, being more efficient with the number of times you need to call AWS, or by increasing the number of hosts sending requests.
	at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:98) ~[sdk-core-2.17.14.jar!/:na]
	at software.amazon.awssdk.core.exception.SdkClientException.create(SdkClientException.java:43) ~[sdk-core-2.17.14.jar!/:na]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.utils.RetryableStageHelper.setLastException(RetryableStageHelper.java:198) ~[sdk-core-2.17.14.jar!/:na]

Caused by: java.lang.Throwable: Acquire operation took longer than the configured maximum time. This indicates that a request cannot get a connection from the pool within the specified maximum time. This can be due to high request rate.
Consider taking any of the following actions to mitigate the issue: increase max connections, increase acquire timeout, or slowing the request rate.
Increasing the max connections can increase client throughput (unless the network interface is already fully utilized), but can eventually start to hit operation system limitations on the number of file descriptors used by the process. If you already are fully utilizing your network interface or cannot further increase your connection count, increasing the acquire timeout gives extra time for requests to acquire a connection before timing out. If the connections doesn't free up, the subsequent requests will still timeout.
If the above mechanisms are not able to fix the issue, try smoothing out your requests so that large traffic bursts cannot overload the client, being more efficient with the number of times you need to call AWS, or by increasing the number of hosts sending requests.
	at software.amazon.awssdk.http.nio.netty.internal.NettyRequestExecutor.decorateException(NettyRequestExecutor.java:306) ~[netty-nio-client-2.17.14.jar!/:na]
	at software.amazon.awssdk.http.nio.netty.internal.NettyRequestExecutor.handleFailure(NettyRequestExecutor.java:299) ~[netty-nio-client-2.17.14.jar!/:na]
	... 18 common frames omitted
Caused by: java.util.concurrent.TimeoutException: Acquire operation took longer than 10000 milliseconds.
	at software.amazon.awssdk.http.nio.netty.internal.HealthCheckedChannelPool.timeoutAcquire(HealthCheckedChannelPool.java:77) ~[netty-nio-client-2.17.14.jar!/:na]
	at software.amazon.awssdk.http.nio.netty.internal.HealthCheckedChannelPool.lambda$acquire$0(HealthCheckedChannelPool.java:67) ~[netty-nio-client-2.17.14.jar!/:na]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.65.Final.jar!/:4.1.65.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170) ~[netty-common-4.1.65.Final.jar!/:4.1.65.Final]
	... 6 common frames omitted

2022-02-18 19:10:46.605  INFO 1 --- [tyEventLoop-0-0] d::downloadAndArchiveFunctionWithInstant : | cancel()
2022-02-18 19:10:46.606 ERROR 1 --- [tyEventLoop-0-0] o.c.s.c.h.ArchiveBuildRequestToArchive   : processArchiveBuildRequest error: Unable to execute HTTP request: Acquire operation took longer than the configured maximum time. This indicates that a request cannot get a connection from the pool within the specified maximum time. This can be due to high request rate.
Consider taking any of the following actions to mitigate the issue: increase max connections, increase acquire timeout, or slowing the request rate.
Increasing the max connections can increase client throughput (unless the network interface is already fully utilized), but can eventually start to hit operation system limitations on the number of file descriptors used by the process. If you already are fully utilizing your network interface or cannot further increase your connection count, increasing the acquire timeout gives extra time for requests to acquire a connection before timing out. If the connections doesn't free up, the subsequent requests will still timeout.
If the above mechanisms are not able to fix the issue, try smoothing out your requests so that large traffic bursts cannot overload the client, being more efficient with the number of times you need to call AWS, or by increasing the number of hosts sending requests.
2022-02-18 19:10:46.792  INFO 1 --- [tor-tcp-epoll-4] ArchiveBuildRequestToArchive             : | onNext(Archive(id=1937f8fa-6a6d-4ead-813a-2dadfa7b9455, status=FAILED, type=ALL, hashInfo={"numSamples":188201,"lastUpdated":"2022-02-16T16:39:51.776Z"}, hash=fae62faab62c72f126c9a72184b413d6, objectId=null, createdAt=1645211217, numOfSamples=188201, numOfDownloads=0))
2022-02-18 19:10:46.796  INFO 1 --- [tor-tcp-epoll-4] ArchiveBuildRequestToArchive             : | onComplete()
```
